name: SolidityCore
version: 0.0.2
main: io.github.abdullahcxd.soliditycore.SolidityCore
api-version: '1.21'
description: The library plugin for OSolidity plugins

libraries:
  - com.zaxxer:HikariCP:7.0.2

commands:
  solidity:
    description: The main command for soliditycore library
    aliases:
      - soliditycore
      - sc
      - so